package com.example.cocophraser

object FourThousandWords {
    val words = listOf(
        "abandoned", "absolutely", "accidentally", "according", "achievement", "acquainted", "adjustment",
        "advertising", "afterwards", "agriculture", "altogether", "ambitious", "americans", "ancestors",
        "anniversary", "apartment", "appearance", "appliances", "appreciate", "assignment", "assistance",
        "athletics", "attachment", "attractive", "automobile", "background", "barbecue", "beautifully",
        "beginning", "beneficial", "bothering", "breakfast", "bureaucrat", "calculator", "california",
        "capability", "celebration", "championship", "character", "childhood", "chocolate", "cigarette",
        "collection", "committee", "community", "complaint", "completely", "computer", "congratulate",
        "consequence", "considerable", "consistently", "constitution", "construction", "convenience",
        "cooperation", "cornflakes", "creativity", "curiosity", "curriculum", "definitely", "department",
        "depending", "describing", "dictionary", "difficulty", "disappear", "discussion", "distinction",
        "documentary", "embarrass", "especially", "evaluation", "everybody", "excellent", "existence",
        "experience", "experiment", "explanation", "expression", "fascinating", "frequently", "friendship",
        "furthermore", "generally", "geography", "gradually", "grandfather", "handicraft", "happening",
        "headquarters", "hesitation", "historians", "honestly", "hospitality", "household", "imagination",
        "immediately", "importance", "impossible", "individual", "inevitable", "information", "inspiration",
        "intelligence", "interesting", "interview", "invention", "invitation", "journalism", "laboratory",
        "landscape", "leadership", "liberally", "literature", "machinery", "magnificent", "manufacture",
        "mathematics", "memorandum", "migration", "mysterious", "nationality", "naturally", "navigation",
        "newspaper", "occasional", "opportunity", "organization", "originally", "outstanding", "paragraph",
        "permission", "personally", "photography", "physically", "popularity", "possession", "preference",
        "preparation", "privately", "procedure", "profession", "pronounced", "psychology", "publicity",
        "punctuation", "questionnaire", "reasonable", "recreation", "refrigerator", "relatively", "restaurant",
        "rhythm", "satisfying", "scholarship", "scientific", "secretary", "seriously", "similarity",
        "sincerely", "situation", "statistics", "television", "temperature", "tremendous", "typewriter",
        "universally", "vacation", "vegetables", "vocabulary", "voluntarily", "acquaintance", "agriculture",
        "altogether", "ambulance", "amusement", "anniversary", "apartment", "appearance", "appliances",
        "appreciate", "assignment", "assistance", "athletics", "attachment", "attractive", "automobile",
        "background", "barbecue", "beautifully", "beginning", "beneficial", "bothering", "breakfast",
        "bureaucrat", "calculator", "california", "capability", "celebration", "championship", "character",
        "childhood", "chocolate", "cigarette", "collection", "committee", "community", "complaint",
        "completely", "computer", "congratulate", "consequence", "considerable", "consistently", "constitution",
        "construction", "convenience", "cooperation", "cornflakes", "creativity", "curiosity", "curriculum",
        "definitely", "department", "depending", "describing", "dictionary", "difficulty", "disappear",
        "discussion", "distinction", "documentary", "embarrass", "especially", "evaluation", "everybody",
        "excellent", "existence", "experience", "experiment", "explanation", "expression", "fascinating",
        "frequently", "friendship", "furthermore", "generally", "geography", "gradually", "grandfather",
        "handicraft", "happening", "headquarters", "hesitation", "historians", "honestly", "hospitality",
        "household", "imagination", "immediately", "importance", "impossible", "individual", "inevitable",
        "information", "inspiration", "intelligence", "interesting", "interview", "invention", "invitation",
        "journalism", "laboratory", "landscape", "leadership", "liberally", "literature", "machinery",
        "magnificent", "manufacture", "mathematics", "memorandum", "migration", "mysterious", "nationality",
        "naturally", "navigation", "newspaper", "occasional", "opportunity", "organization", "originally",
        "outstanding", "paragraph", "permission", "personally", "photography", "physically", "popularity",
        "possession", "preference", "preparation", "privately", "procedure", "profession", "pronounced",
        "psychology", "publicity", "punctuation", "questionnaire", "reasonable", "recreation", "refrigerator",
        "relatively", "restaurant", "rhythm", "satisfying", "scholarship", "scientific", "secretary",
        "seriously", "similarity", "sincerely", "situation", "statistics", "television", "temperature",
        "tremendous", "typewriter", "universally", "vacation", "vegetables", "vocabulary", "voluntarily",
        "watermelon", "wonderful", "yesterday", "zoological", "acquaintance", "aggressively", "airplane",
        "altogether", "ambulance", "amusement", "anniversary", "apartment", "appearance", "appliances",
        "appreciate", "assignment", "assistance", "athletics", "attachment", "attractive", "automobile",
        "background", "barbecue", "beautifully", "beginning", "beneficial", "bothering", "breakfast",
        "bureaucrat", "calculator", "california", "capability", "celebration", "championship", "character",
        "childhood", "chocolate", "cigarette", "collection", "committee", "community", "complaint", "completely",
        "computer", "congratulate", "consequence", "considerable", "consistently", "constitution", "construction",
        "convenience", "cooperation", "cornflakes", "creativity", "curiosity", "curriculum", "definitely",
        "department", "depending", "describing", "dictionary", "difficulty", "disappear", "discussion",
        "distinction", "documentary", "embarrass", "especially", "evaluation", "everybody", "excellent",
        "existence", "experience", "experiment", "explanation", "expression", "fascinating", "frequently",
        "friendship", "furthermore", "generally", "geography", "gradually", "grandfather", "handicraft",
        "happening", "headquarters", "hesitation", "historians", "honestly", "hospitality", "household",
        "imagination", "immediately", "importance", "impossible", "individual", "inevitable", "information",
        "inspiration", "intelligence", "interesting", "interview", "invention", "invitation", "journalism",
        "laboratory", "landscape", "leadership", "liberally", "literature", "machinery", "magnificent",
        "manufacture", "mathematics", "memorandum", "migration", "mysterious", "nationality", "naturally",
        "navigation", "newspaper", "occasional", "opportunity", "organization", "originally", "outstanding",
        "paragraph", "permission", "personally", "photography", "physically", "popularity", "possession",
        "preference", "preparation", "privately", "procedure", "profession", "pronounced", "psychology",
        "publicity", "punctuation", "questionnaire", "reasonable", "recreation", "refrigerator", "relatively",
        "restaurant", "rhythm", "satisfying", "scholarship", "scientific", "secretary", "seriously", "similarity",
        "sincerely", "situation", "statistics", "television", "temperature", "tremendous", "typewriter",
        "universally", "vacation", "vegetables", "vocabulary", "voluntarily", "watermelon", "wonderful",
        "yesterday", "zoological", "acquaintance", "agriculture", "altogether", "ambulance", "amusement",
        "anniversary", "apartment", "appearance", "appliances", "appreciate", "assignment", "assistance",
        "athletics", "attachment", "attractive", "automobile", "background", "barbecue", "beautifully",
        "beginning", "beneficial", "bothering", "breakfast", "bureaucrat", "calculator", "california",
        "capability", "celebration", "championship", "character", "childhood", "chocolate", "cigarette",
        "collection", "committee", "community", "complaint", "completely", "computer", "congratulate",
        "consequence", "considerable", "consistently", "constitution", "construction", "convenience",
        "cooperation", "cornflakes", "creativity", "curiosity", "curriculum", "definitely", "department",
        "depending", "describing", "dictionary", "difficulty", "disappear", "discussion", "distinction",
        "documentary", "embarrass", "especially", "evaluation", "everybody", "excellent", "existence",
        "experience", "experiment", "explanation", "expression", "fascinating", "frequently", "friendship",
        "furthermore", "generally", "geography", "gradually", "grandfather", "handicraft", "happening",
        "headquarters", "hesitation", "historians", "honestly", "hospitality", "household", "imagination",
        "immediately", "importance", "impossible", "individual", "inevitable", "information", "inspiration",
        "intelligence", "interesting", "interview", "invention", "invitation", "journalism", "laboratory",
        "landscape", "leadership", "liberally", "literature", "machinery", "magnificent", "manufacture",
        "mathematics", "memorandum", "migration", "mysterious", "nationality", "naturally", "navigation",
        "newspaper", "occasional", "opportunity", "organization", "originally", "outstanding", "paragraph",
        "permission", "personally", "photography", "physically", "popularity", "possession", "preference",
        "preparation", "privately", "procedure", "profession", "pronounced", "psychology", "publicity",
        "punctuation", "questionnaire", "reasonable", "recreation", "refrigerator", "relatively", "restaurant",
        "rhythm", "satisfying", "scholarship", "scientific", "secretary", "seriously", "similarity",
        "sincerely", "situation", "statistics", "television", "temperature", "tremendous", "typewriter",
        "universally", "vacation", "vegetables", "vocabulary", "voluntarily", "watermelon", "wonderful",
        "yesterday", "zoological", "acquaintance", "aggressively", "airplane", "altogether", "ambulance",
        "amusement", "anniversary","apologetic", "arrangement", "assessment", "assignment", "associate",
        "astonishing", "attendance", "attention", "authentic", "availability", "beneficiary", "benevolent",
        "boulevard", "cancellation", "celebratory", "certification", "championship", "characteristic", "circumstance",
        "collaboration", "communication", "complimentary", "concentration", "congratulation", "consideration",
        "contemporary", "contribution", "cooperation", "correspondence", "determination", "development", "disappointment",
        "discipline", "discovery", "discrimination", "disposition", "diversification", "documentation", "education",
        "efficiency", "elaboration", "electronic", "eligibility", "encouragement", "entertainment", "environment",
        "equivalent", "evaluation", "exaggeration", "examination", "exceptional", "experience", "explanation",
        "expression", "extraordinary", "fabrication", "fascination", "fluctuation", "fundamental", "generation",
        "government", "gratification", "happiness", "harassment", "hospitality", "imagination", "implementation",
        "improvement", "independence", "information", "innovation", "inspiration", "institution", "instruction",
        "intelligence", "interference", "interpretation", "introduction", "investigation", "isolation",
        "journalism", "justification", "legislation", "manipulation", "mathematics", "modification",
        "necessity", "negotiation", "notification", "opportunity", "organization", "participation", "perception",
        "performance", "perpetual", "possibility", "preparation", "presentation", "prevention", "recognition",
        "recommendation", "reconciliation", "registration", "relationship", "representation", "reputation",
        "reservation", "resistance", "resolution", "responsibility", "satisfaction", "significant", "simulation",
        "solicitation", "specialization", "speculation", "substantial", "suggestion", "superintendent",
        "supervision", "supportive", "surveillance", "suspension", "technology", "temperature", "traditional",
        "transaction", "transformation", "transportation", "understanding", "utilization", "verification",
        "vulnerability", "wonderful", "yesterday","anticipation", "appearance", "affectionate", "astonishing",
        "attraction", "authoritative", "backpack", "benevolence", "bewildering", "boisterous", "celebratory",
        "certification", "challenging", "chocolate", "communication", "compassionate", "complimentary",
        "concentration", "congratulation", "consideration", "contemporary", "contribution", "cooperation",
        "correspondence", "decoration", "deliberation", "determination", "development", "disappointment",
        "discipline", "discovery", "discrimination", "disposition", "diversification", "documentation",
        "education", "efficiency", "elaboration", "enthusiasm", "entertainment", "environment", "equivalent",
        "evaluation", "exaggeration", "examination", "exceptional", "experience", "explanation", "expression",
        "extraordinary", "fabrication", "fascination", "fluctuation", "fundamental", "generation", "government",
        "gratification", "happiness", "harassment", "hospitality", "imagination", "implementation", "improvement",
        "independence", "information", "innovation", "inspiration", "institution", "instruction", "intelligence",
        "interference", "interpretation", "introduction", "investigation", "isolation", "justification",
        "legislation", "manipulation", "modification", "notification", "participation", "perception",
        "performance", "perpetual", "possibility", "preparation", "presentation", "prevention", "recognition",
        "recommendation", "reconciliation", "registration", "relationship", "representation", "reputation",
        "reservation", "resistance", "resolution", "responsibility", "satisfaction", "significant", "simulation",
        "solicitation", "specialization", "speculation", "substantial", "suggestion", "superintendent",
        "supervision", "supportive", "surveillance", "suspension", "technology", "traditional", "transaction",
        "transformation", "transportation", "understanding", "utilization", "verification", "vulnerability",
        "abundance", "achievement", "adaptation", "advertisement", "agreement", "alleviate", "announcement",
        "anticipation", "apology", "apprehension", "architecture", "assortment", "atmosphere", "authentication",
        "authorization", "beautiful", "beneficiary", "bewilderment", "boulevard", "brilliant", "calculations",
        "capability", "captivating", "celebration", "challenging", "championship", "characteristic",
        "circumstance", "collaboration", "communication", "complimentary", "concentration", "congratulation",
        "consideration", "contemporary", "contribution", "cooperation", "correspondence", "declaration",
        "deliberation", "determination", "development", "disappointment", "discipline", "discovery",
        "discrimination", "disposition", "diversification", "documentation", "education", "efficiency",
        "elaboration", "emphasize", "encouragement", "enthusiasm", "entertainment", "environment", "equivalent",
        "evaluation", "exaggeration", "examination", "exceptional", "experience", "explanation", "expression",
        "extraordinary", "fabrication", "fascination", "fluctuation", "fundamental", "generation", "government",
        "gratification", "happiness", "harassment", "hospitality", "imagination", "implementation", "improvement",
        "independence", "information", "innovation", "inspiration", "institution", "instruction", "intelligence",
        "interference", "interpretation", "introduction", "investigation", "isolation", "justification",
        "legislation", "manipulation", "modification", "necessity", "negotiation", "notification", "opportunity",
        "organization", "participation", "perception", "performance", "perpetual", "possibility", "preparation",
        "presentation", "prevention", "recognition", "recommendation", "reconciliation", "registration",
        "relationship", "representation", "reputation", "reservation", "resistance", "resolution", "responsibility",
        "satisfaction", "significant", "simulation", "solicitation", "specialization", "speculation",
        "substantial", "suggestion", "superintendent", "supervision", "supportive", "surveillance", "suspension",
        "technology", "temperature", "traditional", "transaction", "transformation", "transportation",
        "understanding", "utilization", "verification", "vulnerability", "abandon", "ability", "abortion",
        "about", "above", "abroad", "absence", "absolute", "absolutely", "absorb", "abuse", "academic",
        "accept", "access", "accident", "accompany", "accomplish", "according", "account", "accurate",
        "accuse", "achieve", "achievement", "acknowledge", "acquire", "across", "action", "active", "activist",
        "activity", "actor", "actress", "actual", "actually", "adapt", "addition", "additional", "address",
        "adequate", "adjust", "adjustment", "administration", "administrator", "admire", "admission", "admit",
        "adolescent", "adopt", "adult", "advance", "advanced", "advantage", "adventure", "advertising", "advice",
        "advise", "adviser", "advocate", "affect", "afford", "afraid", "African", "African-American", "afternoon",
        "against", "agency", "agenda", "agent", "aggressive", "aircraft", "airline", "airport", "alcohol",
        "alliance", "allow", "almost", "along", "already", "alter", "alternative", "although", "always", "amazing",
        "American", "among", "amount", "analysis", "analyst", "analyze", "ancient", "anger", "angle", "angry",
        "animal", "anniversary", "announce", "annual", "another", "answer", "anticipate", "anxiety", "anybody",
        "anymore", "anyone", "anything", "anyway", "anywhere", "apart", "apartment", "apparent", "apparently",
        "appear", "appearance", "application", "apply", "appoint", "appointment", "appreciate", "approach", "appropriate",
        "approval", "approve", "approximately", "architect", "argument", "arrange", "arrangement", "arrest", "arrival",
        "arrive", "article", "artist", "artistic", "asleep", "aspect", "assault", "assert", "assess", "assessment",
        "assign", "assignment", "assist", "assistance", "assistant", "associate", "association", "assume", "assumption",
        "assure", "athlete", "athletic", "atmosphere", "attach", "attack", "attempt", "attend", "attention", "attitude",
        "attorney", "attract", "attractive", "attribute", "audience", "author", "authority", "available", "average",
        "avoid", "award", "aware", "awareness", "awful", "background", "badly", "balance", "barely", "barrel", "barrier",
        "baseball", "basically", "basketball", "bathroom", "battery", "battle", "beach", "beautiful", "because", "become",
        "bedroom", "behavior", "behind", "belief", "believe", "belong", "beside", "besides", "better", "between", "beyond",
        "billion", "biological", "birthday", "blanket", "boundary", "boyfriend", "branch", "building", "bullet", "burden",
        "business", "butter", "cabinet", "calculate", "camera", "campaign", "campus", "Canadian", "candidate", "capability",
        "capable", "capacity", "capital", "captain", "capture", "carbon", "career", "careful", "carefully", "carrier",
        "cash", "celebrate", "celebration", "celebrity", "center", "central", "century", "ceremony", "certain", "certainly",
        "chair", "chairman", "challenge", "chamber", "champion", "championship", "change", "changing", "channel",
        "chapter", "character", "characteristic", "characterize", "charge", "charity", "chemical", "chicken", "childhood",
        "Chinese", "chocolate", "choice", "cholesterol", "Christian", "Christmas", "cigarette", "circumstance", "citizen",
        "civilian", "classic", "classroom", "clear", "clearly", "climate", "clinic", "clinical", "clock", "closer",
        "clothes", "clothing", "cluster", "coach", "coalition", "collapse", "colleague", "collective", "colonial",
        "column", "combination", "combine", "comedy", "comfort", "comfortable", "commander", "commercial", "commission",
        "commitment", "committee", "communicate", "communication", "community", "comparison", "competition", "competitive",
        "complain", "complaint", "complete", "completely", "complex", "complicated", "component", "compose", "composition",
        "comprehensive", "computer", "concentration", "concept", "concern", "concerned", "conclude", "conclusion", "concrete",
        "condition", "conduct", "conference", "confidence", "confident", "confirm", "conflict", "confront", "Congress",
        "congressional", "connection", "consciousness", "consensus", "consequence", "conservative", "considerable", "consideration",
        "consistent", "constant", "constantly", "constitutional", "construction", "consultant", "consumer", "consumption", "container",
        "contemporary", "content", "context", "continued", "contrast", "contribute", "contribution", "controversial", "controversy", "convention", "conventional", "conversation", "conviction", "convince", "cookie", "cooperation", "counselor", "council", "count", "counter", "coverage", "courage", "corporate", "correspondent", "cotton", "council", "course", "cousin", "coverage", "crack", "craft", "crash", "crazy", "cream", "create", "creation", "creative", "creature", "credit", "crew", "crime", "criminal", "crisis", "criteria", "critic", "critical", "criticism", "criticize", "crop", "cross", "crowd", "crucial", "cultural", "culture", "curious", "current", "currently", "curriculum", "custom", "customer", "cycle", "daily", "damage", "dance", "danger", "dangerous", "data", "date", "daughter", "dead", "deal", "dealer", "dear", "death", "debate", "debt", "decade", "decide", "decision", "deck", "declare", "decline", "decrease", "deep", "deeply", "deer", "defeat", "defend", "defendant", "defense", "defensive", "deficit", "define", "definitely", "definition", "degree", "delay", "deliver", "delivery", "demand", "democracy", "democrat", "democratic", "demonstrate", "demonstration", "deny", "department", "depend", "dependent", "depending", "depict", "depression", "depth", "deputy", "derive", "describe", "description", "desert", "deserve", "design", "designer", "desire", "desk", "desperate", "despite", "destroy", "destruction", "detail", "detailed", "detect", "determine", "develop", "developing", "development", "device", "devote", "dialogue", "differ", "difference", "different", "differently", "difficult", "difficulty", "digital", "dimension", "dining", "dinner", "direct", "direction", "directly", "director", "dirt", "dirty", "disability", "disagree", "disappear", "disaster", "discipline", "discourse", "discover", "discovery", "discrimination", "discuss", "discussion", "disease", "dish", "dismiss", "disorder", "display", "dispute", "distance", "distant", "distinct", "distinction", "distinguish", "distribute", "distribution", "district", "diverse", "diversity", "divide", "division", "divorce", "doctor", "document", "domestic", "dominant", "dominate", "double", "doubt", "downtown", "dozen", "draft", "drama", "dramatic", "dramatically", "draw", "drawing", "dream", "dress", "drink", "drive", "driver", "drop", "drug", "duty", "each", "eager", "early", "earn", "earnings", "earth", "ease", "easily", "eastern", "economic", "economics", "economist", "economy", "edge", "edition", "editor", "educate", "education", "educational", "educator", "effect", "effective", "effectively", "efficiency", "efficient", "effort", "eight", "either", "elderly", "elect", "election", "electric", "electricity", "electronic", "element", "elementary", "eliminate", "elite", "elsewhere", "embrace", "emerge", "emergency", "emission", "emotion", "emotional", "emphasis", "emphasize", "employ", "employee", "employer", "employment", "enable", "encounter", "encourage", "enemy", "energy", "enforcement", "engage", "engine", "engineer", "engineering", "enhance", "enjoy", "enormous", "ensure", "enter", "enterprise", "entertainment", "entire", "environment", "environmental", "episode", "equal", "equally", "equipment", "error", "escape", "especially", "essay", "essential", "essentially", "establish", "establishment", "estate", "estimate", "ethics", "ethnic", "European", "evaluate", "evaluation", "evening", "event", "eventually", "everyone", "everything", "evidence", "evolution", "exactly", "examination", "example", "exceed", "excellent", "exception", "exchange", "exciting", "executive", "exercise", "exhibit", "exhibition", "existence", "existing", "expand", "expansion", "expect", "expectation", "expense", "expensive", "experience", "experiment", "expert", "explain", "explanation", "explode", "explore", "explosion", "expose", "exposure", "express", "expression", "extend", "extension", "extensive", "extent", "external", "extra", "extreme", "extremely", "fabric", "facility", "factor", "factory", "faculty", "failure", "familiar", "family", "famous", "fantasy", "farmer", "fashion", "federal", "feeling", "fellow", "fence", "fiber", "fiction", "field", "fifteen", "fifth", "fifty", "fighter", "figure", "final", "finance", "financial", "finding", "finger", "finish", "firm", "first", "fishing", "fitness", "flavor", "flight", "float", "floor", "flower", "focus", "follow", "following", "football", "force", "foreign", "forest", "forever", "forget", "formal", "former", "formula", "forth", "fortune", "forward", "foundation", "founder", "fourth", "frame", "framework", "freedom", "freeze", "French", "frequency", "frequent", "frequently", "friend", "friendly", "friendship", "fruit", "frustration", "funding", "funeral", "furniture", "furthermore", "future", "galaxy", "gallery", "gang", "garden", "garlic", "gather", "gender", "general", "generally", "generate", "generation", "genetic", "gentleman", "German", "gesture", "ghost", "giant", "gifted", "girlfriend", "greatest", "grocery", "group", "growing", "guarantee", "guideline", "guilty", "habit", "habitat", "handful", "handle", "happen", "healthy", "hearing", "headline", "headquarters", "healthy", "heritage", "herself", "hide", "highlight", "highly", "highway", "himself", "hire", "historian", "historic", "historical", "history", "holiday", "homeless", "honest", "honey", "honor", "horizon", "horror", "hospital", "household", "housing", "however", "human", "humor", "hundred", "hungry", "hunter", "hunting", "husband", "hypothesis", "ideal", "identification", "identify", "identity", "ignore", "illegal", "illness", "illustrate", "imagination", "imagine", "immediate", "immediately", "immigrant", "immigration", "impact", "implement", "implication", "importance", "important", "impose", "impossible", "impress", "impression", "impressive", "improve", "improvement", "incentive", "incident", "including", "income", "incorporate", "increase", "increased", "increasing", "incredible", "indeed", "independence", "independent", "indicate", "indication", "individual", "industrial", "industry", "infection", "inflation", "influence", "inform", "information", "ingredient", "initial", "initially", "initiative", "injury", "innocent", "inquiry", "inside", "insight", "insist", "inspire", "install", "instance", "instead", "institution", "institutional", "instruction", "instructor", "instrument", "insurance", "intellectual", "intelligence", "intend", "intense", "intensity", "intention", "interaction", "interest", "interested", "interesting", "internal", "international", "Internet", "interpret", "interpretation", "intervention", "interview", "introduce", "introduction", "invasion", "investigate", "investigation", "investigator", "investment", "investor", "invite", "involve", "involved", "involvement", "Iraqi", "Irish", "Island", "Israeli", "issue", "Italian", "itself", "jacket", "Japanese", "Jewish", "joint", "journal", "journalist", "journey", "judgment", "juice", "junior", "jury", "justice", "justify", "keeping", "key", "kick", "kid", "killer", "killing", "kind", "king", "kiss", "kitchen", "knee", "knife", "knock", "knowledge", "label", "labor", "laboratory", "lady", "landscape", "language", "large", "largely", "Latin", "latter", "launch", "lawsuit", "lawyer", "layer", "leader", "leadership", "leading", "league", "learn", "learning", "leather", "leave", "legacy", "legal", "legend", "legislation", "legitimate", "length", "lesson", "letter", "liberal", "library", "license", "lifetime", "likely", "limit", "limitation", "limited", "literally", "literary", "literature", "little", "living", "location", "locker", "long-term", "loose", "loss", "lots", "loud", "lovely", "machine", "magazine", "mailbox", "mainly", "maintain", "major", "majority", "maker", "makeup", "male", "manage", "management", "manager", "manner", "manufacturer", "manufacturing", "margin", "marketing", "marriage", "married", "marry", "massive", "master", "match", "material", "maybe", "mayor", "meaning", "meanwhile", "measure", "measurement", "mechanism", "media", "medical", "medication", "medicine", "medium", "meeting", "member", "membership", "memory", "mental", "mention", "message", "metal", "meter", "method", "Mexican", "middle", "might", "military", "million", "minister", "minority", "minute", "miracle", "mirror", "missile", "mission", "mistake", "mixture", "moderate", "modern", "moment", "money", "monitor", "morning", "mortgage", "mostly", "motion", "motivation", "motor", "mountain", "muscle", "museum", "musical", "musician", "Muslim", "myself", "mystery", "naked", "name", "narrative", "narrow", "national", "natural", "naturally", "nature", "nearby", "nearly", "necessarily", "necessary", "negative", "negotiate", "negotiation", "neighbor", "neighborhood", "neither", "nervous", "network", "nevertheless", "newly", "newspaper", "night", "nobody", "noise", "nomination", "nonetheless", "normal", "normally", "northern", "nothing", "notice", "notion", "novel", "nuclear", "number", "numerous", "object", "objective", "obligation", "observation", "observer", "obtain", "obvious", "obviously", "occasion", "occasionally", "occupation", "occur", "ocean", "offense", "offensive", "office", "officer", "official", "often", "Olympic", "ongoing", "online", "opening", "operate", "operation", "operator", "opinion", "opponent", "opportunity", "oppose", "opposite", "opposition", "option", "orange", "order", "ordinary", "organic", "organization", "organize", "orientation", "origin", "original", "originally", "others", "otherwise", "ought", "ourselves", "outcome", "outside", "overall", "overcome", "overlook", "owner", "package", "painful", "painter", "painting", "Palestinian", "paper", "parent", "parking", "participant", "participate", "participation", "particular", "particularly", "partner", "partnership", "passage", "passenger", "passion", "pattern", "patient", "pattern", "payment", "peace", "people", "perceive", "percentage", "perception", "perfect", "perfectly", "perform", "performance", "perhaps", "period", "permanent", "permission", "permit", "person", "personal", "personality", "personnel", "perspective", "persuade", "phase", "phenomenon", "philosophy", "photo", "photograph", "photographer", "phrase", "physical", "physician", "picture", "piece", "pilot", "pitch", "plane", "planet", "plastic", "plate", "platform", "player", "please", "pleasure", "plenty", "pocket", "poem", "poetry", "point", "police", "policy", "political", "politician", "politics", "pollution", "popular", "population", "portion", "portrait", "position", "positive", "possess", "possibility", "possible", "possibly", "potato", "potential", "potentially", "pound", "poverty", "powder", "powerful", "practical", "practice", "prayer", "precisely", "predict", "prefer", "preference", "pregnancy", "pregnant", "preparation", "prepare", "prescription", "presence", "present", "presentation", "preserve", "president", "presidential", "pressure", "pretend", "pretty", "prevent", "previous", "previously", "problem", "procedure", "proceed", "process", "produce", "producer", "product", "production", "profession", "professional", "professor", "profile", "profit", "program", "progress", "project", "prominent", "promise", "promote", "prompt", "property", "proportion", "proposal", "prosecutor", "prospect", "protect", "protection", "protein", "protest", "provide", "provider", "province", "provision", "psychological", "psychologist", "psychology", "publication", "publisher", "punishment", "purchase", "purpose", "pursue", "question", "quickly", "quietly", "rather", "rating", "reach", "reaction", "reader", "reading", "realize", "really", "reasonable", "recall", "receive", "recent", "recently", "recipe", "recognition", "recognize", "recommend", "recommendation", "record", "recording", "recover", "recovery", "recruit", "reduce", "reduction", "reference", "reflect", "reflection", "regard", "regarding", "regardless", "region", "regional", "register", "regular", "regularly", "regulate", "regulation", "reinforce", "relate", "relation", "relationship", "relative", "relatively", "release", "relevant", "relief", "religion", "religious", "remain", "remaining", "remarkable", "remember", "remote", "remove", "repeat", "repeatedly", "replace", "reporter", "represent", "representation", "representative", "Republican", "reputation", "request", "require", "requirement", "research", "researcher", "resemble", "reservation", "resident", "resist", "resistance", "resolution", "resolve", "resource", "respond", "respondent", "response", "responsibility", "responsible", "restaurant", "restore", "restriction", "result", "retain", "retire", "retirement", "return", "reveal", "revenue", "review", "revolution", "rhythm", "rice", "ride", "rifle", "right", "rise", "risk", "river", "road", "rock", "role", "roll", "romantic", "roof", "room", "root", "rope", "rough", "round", "route", "routine", "rub", "rule", "running", "rural", "Russian", "sacred", "safety", "salad", "salary", "sales", "satisfaction", "satisfy", "sauce", "saving", "scale", "scandal", "scared", "scenario", "scene", "schedule", "scheme", "scholar", "school", "science", "scientific", "scientist", "scope", "score", "scream", "screen", "script", "search", "season", "second", "secret", "secretary", "section", "sector", "secure", "security", "segment", "select", "selection", "Senate", "senator", "send", "senior", "sense", "sensitive", "sentence", "separate", "sequence", "series", "serious", "seriously", "serve", "service", "session", "setting", "settle", "settlement", "seven", "several", "severe", "sexual", "shade", "shadow", "shape", "share", "sharp", "sheet", "shelf", "shell", "shelter", "shift", "shine", "shirt", "shit", "shock", "shoot", "shooting", "shopping", "shore", "short", "should", "shoulder", "shout", "show", "shower", "shrug", "sick", "sigh", "sight", "sign", "signal", "significance", "significant", "significantly", "silence", "silent", "silver", "similar", "similarly", "simple", "simply", "sing", "singer", "single", "sink", "sister", "situation", "size", "skin", "slave", "slice", "slide", "slight", "slightly", "slip", "slow", "small", "smart", "smell", "smile", "smoke", "smooth", "snow", "soccer", "social", "society", "software", "soldier", "solid", "solution", "solve", "somebody", "somehow", "someone", "something", "sometimes", "somewhat", "somewhere", "sophisticated", "sorry", "soul", "sound", "soup", "source", "south", "southern", "Soviet", "space", "Spanish", "speak", "speaker", "special", "specialist", "species", "specific", "specifically", "speech", "speed", "spend", "spending", "spirit", "spiritual", "split", "spokesman", "sport", "spread", "spring", "square", "squeeze", "stability", "stable", "staff", "stage", "stair", "stake", "stand", "standard", "standing", "stare", "start", "state", "statement", "station", "statistics", "status", "steady", "steal", "steel", "stick", "still", "stock", "stomach", "stone", "storage", "store", "storm", "story", "straight", "strange", "stranger", "strategic", "strategy", "stream", "street", "strength", "strengthen", "stress", "stretch", "strike", "string", "strip", "stroke", "strong", "structure", "struggle", "student", "studio", "study", "stuff", "stupid", "style", "subject", "submit", "subsequent", "substance", "substantial", "succeed", "success", "successful", "such", "sudden", "suddenly", "suffer", "sufficient", "suggest", "suggestion", "suicide", "summer", "summit", "super", "supply", "support", "supporter", "suppose", "supposed", "Supreme", "surely", "surface", "surgery", "surprise", "surprised", "surprising", "surprisingly", "surround", "survey", "survival", "survive", "survivor", "suspect", "sustain", "sweep", "sweet", "swing", "switch", "symbol", "symptom", "system", "table", "tablespoon", "tactic", "tail", "taste", "taxpayer", "teach", "teacher", "teaching", "television", "temperature", "temporary", "tendency", "teenager", "telephone", "telescope", "television", "temperature", "temporary", "tendency", "teenager", "telephone", "telescope", "television", "temperature", "temporary", "tendency", "tennis", "tension", "territory", "terrorism", "terrorist", "testify", "testimony", "testing", "thank", "thanks", "theater", "their", "theme", "theory", "therapy", "therefore", "these", "thick", "thing", "think", "thinking", "third", "thousand", "threaten", "throughout", "ticket", "time", "together", "tomato", "tomorrow", "tonight", "tool", "total", "totally", "touch", "tough", "tourist", "tournament", "toward", "towards", "traffic", "tragedy", "training", "transfer", "transform", "transition", "translate", "transportation", "treaty", "tremendous", "typical", "typically", "ultimate", "ultimately", "understand", "understanding", "unfortunately", "uniform", "unique", "universal", "universe", "university", "unusual", "unless", "unlikely", "unusual", "upper", "urban", "useful", "useful", "usually", "vacation", "valuable", "variable", "variation", "variety", "various", "victim", "victory", "viewer", "village", "violate", "violation", "violence", "violent", "virtually", "virtue", "volunteer", "vulnerable", "warning", "waste", "wealth", "wealthy", "weapon", "weather", "wedding", "weekly", "weigh", "welcome", "welfare", "western", "widespread", "whisper", "whose", "widely", "winter", "witness", "wonderful", "wooden", "worker", "working", "workshop", "worried", "worth", "would", "write", "writer", "writing", "yellow", "yesterday", "yield", "young", "yours", "yourself"
    )
}